# 调低 thermal_zone0 的 PWM 风扇温控阈值 (NanoPC-T4)
# trip_point_3 (cpu_warm): 风扇低速档起转温度 (原厂 55°C，现改 45°C)
w /sys/devices/virtual/thermal/thermal_zone0/trip_point_3_temp - - - - 45000
# trip_point_4 (cpu_hot): 风扇中高速档提速温度 (原厂 65°C，现改 49°C)
w /sys/devices/virtual/thermal/thermal_zone0/trip_point_4_temp - - - - 49000
