# Type Path Mode User Group Age Argument
d /storage/.cache/vim/swap 0700 root root -
d /storage/.cache/vim/backup 0700 root root -
d /storage/.cache/vim/undo 0700 root root -

# Fix for Vim versions that don't auto-search .config
L+ /storage/.vimrc - - - - /storage/.config/vim/vimrc
