# Type  Path                          Mode  User             Group            Age  Argument
d /storage/.cache/coredump 0755 systemd-coredump systemd-coredump -
L+ /var/lib/systemd/coredump - - - - /storage/.cache/coredump
